apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email để nhận thông báo về certificate expiry
    email: lanie.071004@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    # Thay đổi từ http01 sang dns01
    - dns01:
        cloudflare:
          email: lanie.071004@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
        - chickenkiller.com